ansible-playbook [core 2.14.18]
  config file = None
  configured module search path = ['/home/vboxuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/vboxuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
host_list declined parsing /home/vboxuser/drupal-ansible/inventory.ini as it did not pass its verify_file() method
script declined parsing /home/vboxuser/drupal-ansible/inventory.ini as it did not pass its verify_file() method
auto declined parsing /home/vboxuser/drupal-ansible/inventory.ini as it did not pass its verify_file() method
yaml declined parsing /home/vboxuser/drupal-ansible/inventory.ini as it did not pass its verify_file() method
Parsed /home/vboxuser/drupal-ansible/inventory.ini inventory source with ini plugin
ERROR! the role 'Set correct permissions' was not found in /home/vboxuser/drupal-ansible/roles:/home/vboxuser/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/vboxuser/drupal-ansible

The error appears to be in '/home/vboxuser/drupal-ansible/playbook.yml': line 63, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: Set correct permissions
      ^ here
